// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: complaints.sql

package database

import (
	"context"
	"database/sql"
)

const createPlayerComplaint = `-- name: CreatePlayerComplaint :one
INSERT INTO complaints (action_id, target_id)
VALUES (
    $1,
    $2
)
RETURNING id, created_at, action_id, target_id
`

type CreatePlayerComplaintParams struct {
	ActionID int32
	TargetID sql.NullInt32
}

func (q *Queries) CreatePlayerComplaint(ctx context.Context, arg CreatePlayerComplaintParams) (Complaint, error) {
	row := q.db.QueryRowContext(ctx, createPlayerComplaint, arg.ActionID, arg.TargetID)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ActionID,
		&i.TargetID,
	)
	return i, err
}

const deletePlayerComplaint = `-- name: DeletePlayerComplaint :exec
DELETE FROM complaints
WHERE action_id=$1
`

func (q *Queries) DeletePlayerComplaint(ctx context.Context, actionID int32) error {
	_, err := q.db.ExecContext(ctx, deletePlayerComplaint, actionID)
	return err
}

const getPlayerComplaints = `-- name: GetPlayerComplaints :one
SELECT id, created_at, action_id, target_id FROM complaints
WHERE action_id=$1
`

func (q *Queries) GetPlayerComplaints(ctx context.Context, actionID int32) (Complaint, error) {
	row := q.db.QueryRowContext(ctx, getPlayerComplaints, actionID)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ActionID,
		&i.TargetID,
	)
	return i, err
}
