// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: elevations.sql

package database

import (
	"context"
)

const createPlayerEPSubmission = `-- name: CreatePlayerEPSubmission :one
INSERT INTO elevation_points (action_id)
VALUES (
    $1
)
RETURNING id, created_at, action_id, ep_linguistics, ep_arithmetics, ep_rhetoric_and_logic, ep_archives, ep_sympathy, ep_physicking, ep_alchemy, ep_artificery, ep_naming
`

func (q *Queries) CreatePlayerEPSubmission(ctx context.Context, actionID int32) (ElevationPoint, error) {
	row := q.db.QueryRowContext(ctx, createPlayerEPSubmission, actionID)
	var i ElevationPoint
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ActionID,
		&i.EpLinguistics,
		&i.EpArithmetics,
		&i.EpRhetoricAndLogic,
		&i.EpArchives,
		&i.EpSympathy,
		&i.EpPhysicking,
		&i.EpAlchemy,
		&i.EpArtificery,
		&i.EpNaming,
	)
	return i, err
}

const getPlayerEPByPlayerActionID = `-- name: GetPlayerEPByPlayerActionID :one
SELECT id, created_at, action_id, ep_linguistics, ep_arithmetics, ep_rhetoric_and_logic, ep_archives, ep_sympathy, ep_physicking, ep_alchemy, ep_artificery, ep_naming FROM elevation_points
WHERE action_id=$1 LIMIT 1
`

func (q *Queries) GetPlayerEPByPlayerActionID(ctx context.Context, actionID int32) (ElevationPoint, error) {
	row := q.db.QueryRowContext(ctx, getPlayerEPByPlayerActionID, actionID)
	var i ElevationPoint
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ActionID,
		&i.EpLinguistics,
		&i.EpArithmetics,
		&i.EpRhetoricAndLogic,
		&i.EpArchives,
		&i.EpSympathy,
		&i.EpPhysicking,
		&i.EpAlchemy,
		&i.EpArtificery,
		&i.EpNaming,
	)
	return i, err
}

const updatePlayerEPSubmission = `-- name: UpdatePlayerEPSubmission :one
UPDATE elevation_points SET (ep_linguistics, ep_arithmetics, ep_rhetoric_and_logic, ep_archives, ep_sympathy, ep_physicking, ep_alchemy, ep_artificery, ep_naming)
= (
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
) WHERE action_id=$1
RETURNING id, created_at, action_id, ep_linguistics, ep_arithmetics, ep_rhetoric_and_logic, ep_archives, ep_sympathy, ep_physicking, ep_alchemy, ep_artificery, ep_naming
`

type UpdatePlayerEPSubmissionParams struct {
	ActionID           int32
	EpLinguistics      int32
	EpArithmetics      int32
	EpRhetoricAndLogic int32
	EpArchives         int32
	EpSympathy         int32
	EpPhysicking       int32
	EpAlchemy          int32
	EpArtificery       int32
	EpNaming           int32
}

func (q *Queries) UpdatePlayerEPSubmission(ctx context.Context, arg UpdatePlayerEPSubmissionParams) (ElevationPoint, error) {
	row := q.db.QueryRowContext(ctx, updatePlayerEPSubmission,
		arg.ActionID,
		arg.EpLinguistics,
		arg.EpArithmetics,
		arg.EpRhetoricAndLogic,
		arg.EpArchives,
		arg.EpSympathy,
		arg.EpPhysicking,
		arg.EpAlchemy,
		arg.EpArtificery,
		arg.EpNaming,
	)
	var i ElevationPoint
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ActionID,
		&i.EpLinguistics,
		&i.EpArithmetics,
		&i.EpRhetoricAndLogic,
		&i.EpArchives,
		&i.EpSympathy,
		&i.EpPhysicking,
		&i.EpAlchemy,
		&i.EpArtificery,
		&i.EpNaming,
	)
	return i, err
}
