// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_turns.sql

package database

import (
	"context"
	"database/sql"
)

const getGameTurns = `-- name: GetGameTurns :many
SELECT id, created_at, game_id, name, writeup, term, month FROM game_turns
WHERE game_id = $1
`

func (q *Queries) GetGameTurns(ctx context.Context, gameID int32) ([]GameTurn, error) {
	rows, err := q.db.QueryContext(ctx, getGameTurns, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameTurn
	for rows.Next() {
		var i GameTurn
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.GameID,
			&i.Name,
			&i.Writeup,
			&i.Term,
			&i.Month,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newGameTurn = `-- name: NewGameTurn :one
INSERT INTO game_turns (game_id, name, term, month)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, created_at, game_id, name, writeup, term, month
`

type NewGameTurnParams struct {
	GameID int32
	Name   sql.NullString
	Term   int32
	Month  int32
}

func (q *Queries) NewGameTurn(ctx context.Context, arg NewGameTurnParams) (GameTurn, error) {
	row := q.db.QueryRowContext(ctx, newGameTurn,
		arg.GameID,
		arg.Name,
		arg.Term,
		arg.Month,
	)
	var i GameTurn
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.GameID,
		&i.Name,
		&i.Writeup,
		&i.Term,
		&i.Month,
	)
	return i, err
}
