// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const clearGames = `-- name: ClearGames :exec
DELETE FROM games
`

func (q *Queries) ClearGames(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearGames)
	return err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (id, created_at, game_master, name, type, type_number)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, game_master, name, type, type_number
`

type CreateGameParams struct {
	ID         int32
	CreatedAt  time.Time
	GameMaster int32
	Name       sql.NullString
	Type       sql.NullString
	TypeNumber sql.NullString
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.ID,
		arg.CreatedAt,
		arg.GameMaster,
		arg.Name,
		arg.Type,
		arg.TypeNumber,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.GameMaster,
		&i.Name,
		&i.Type,
		&i.TypeNumber,
	)
	return i, err
}

const getGamer = `-- name: GetGamer :one
SELECT id, created_at, game_master, name, type, type_number FROM games
WHERE id=$1 LIMIT 1
`

func (q *Queries) GetGamer(ctx context.Context, id int32) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGamer, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.GameMaster,
		&i.Name,
		&i.Type,
		&i.TypeNumber,
	)
	return i, err
}

const getGames = `-- name: GetGames :many
SELECT id, created_at, game_master, name, type, type_number FROM games
`

func (q *Queries) GetGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, getGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.GameMaster,
			&i.Name,
			&i.Type,
			&i.TypeNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
