// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ClassType string

const (
	ClassTypeVintishNobleman  ClassType = "vintish_nobleman"
	ClassTypeAturanNobleman   ClassType = "aturan_nobleman"
	ClassTypeYllishCommoner   ClassType = "yllish_commoner"
	ClassTypeCealdishCommoner ClassType = "cealdish_commoner"
	ClassTypeEdemaRuh         ClassType = "edema_ruh"
)

func (e *ClassType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClassType(s)
	case string:
		*e = ClassType(s)
	default:
		return fmt.Errorf("unsupported scan type for ClassType: %T", src)
	}
	return nil
}

type NullClassType struct {
	ClassType ClassType
	Valid     bool // Valid is true if ClassType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClassType) Scan(value interface{}) error {
	if value == nil {
		ns.ClassType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClassType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClassType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClassType), nil
}

type LodgingType string

const (
	LodgingTypeStreets         LodgingType = "streets"
	LodgingTypeUnderthing      LodgingType = "underthing"
	LodgingTypeMews            LodgingType = "mews"
	LodgingTypeAnkers          LodgingType = "ankers"
	LodgingTypeKingsDrab       LodgingType = "kings_drab"
	LodgingTypeGreyMan         LodgingType = "grey_man"
	LodgingTypeGoldenPony      LodgingType = "golden_pony"
	LodgingTypeWindyTower      LodgingType = "windy_tower"
	LodgingTypeHorseAndFour    LodgingType = "horse_and_four"
	LodgingTypePearlOfImre     LodgingType = "pearl_of_imre"
	LodgingTypeSpindleAndDraft LodgingType = "spindle_and_draft"
)

func (e *LodgingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LodgingType(s)
	case string:
		*e = LodgingType(s)
	default:
		return fmt.Errorf("unsupported scan type for LodgingType: %T", src)
	}
	return nil
}

type NullLodgingType struct {
	LodgingType LodgingType
	Valid       bool // Valid is true if LodgingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLodgingType) Scan(value interface{}) error {
	if value == nil {
		ns.LodgingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LodgingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLodgingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LodgingType), nil
}

type Action struct {
	ID               int32
	CreatedAt        time.Time
	PlayerTurnID     sql.NullInt32
	Lodging          NullLodgingType
	VisitImre        sql.NullBool
	AttendUniversity sql.NullBool
}

type Complaint struct {
	ID        int32
	CreatedAt time.Time
	ActionID  sql.NullInt32
	TargetID  sql.NullInt32
}

type Contract struct {
	ID                 int32
	CreatedAt          time.Time
	GameID             sql.NullInt32
	Name               sql.NullString
	Description        sql.NullString
	RequestingPlayerID sql.NullInt32
	AcceptedPlayerID   sql.NullInt32
	BountyCoin         sql.NullFloat64
	BountyItem         sql.NullString
}

type ElevationPoint struct {
	ID                 int32
	CreatedAt          time.Time
	ActionID           sql.NullInt32
	EpLinguistics      sql.NullInt32
	EpArithmetics      sql.NullInt32
	EpRhetoricAndLogic sql.NullInt32
	EpArchives         sql.NullInt32
	EpSympathy         sql.NullInt32
	EpPhysicking       sql.NullInt32
	EpAlchemy          sql.NullInt32
	EpArtificery       sql.NullInt32
	EpNaming           sql.NullInt32
}

type Game struct {
	ID         int32
	CreatedAt  time.Time
	GameMaster int32
	Name       sql.NullString
	Type       sql.NullString
	TypeNumber sql.NullString
}

type ImreAction struct {
	ID                         int32
	CreatedAt                  time.Time
	ActionID                   sql.NullInt32
	EolianPipes                sql.NullBool
	EolianPractice             sql.NullBool
	GilesLoan                  sql.NullFloat64
	DeviLoan                   sql.NullFloat64
	DiceBet                    sql.NullFloat64
	NoxNahlrout                sql.NullInt32
	NoxCouriers                sql.NullInt32
	NoxBloodless               sql.NullInt32
	NoxGram                    sql.NullInt32
	BlackMarketMommet          sql.NullInt32
	BlackMarketBodyguard       sql.NullBool
	BlackMarketBodygaurdTarget sql.NullInt32
	BlackMarketAssassin        sql.NullBool
	BlackMarketAssassinTarget  sql.NullInt32
	BlackMarketContracts       sql.NullBool
}

type ImreContractAction struct {
	ID           int32
	CreatedAt    time.Time
	ImreActionID sql.NullInt32
	ContractID   sql.NullInt32
}

type Player struct {
	ID         int32
	CreatedAt  time.Time
	UserID     int32
	GameID     int32
	Name       sql.NullString
	Skindancer sql.NullBool
	Class      NullClassType
}

type PlayerStatus struct {
	ID                 int32
	CreatedAt          time.Time
	TurnID             sql.NullInt32
	Alive              sql.NullBool
	Sane               sql.NullBool
	Crockery           sql.NullBool
	Lodging            sql.NullBool
	Imre               sql.NullBool
	University         sql.NullBool
	Medica             sql.NullBool
	Coin               sql.NullFloat64
	EpLinguistics      sql.NullInt32
	EpArithmetics      sql.NullInt32
	EpRhetoricAndLogic sql.NullInt32
	EpArchives         sql.NullInt32
	EpSympathy         sql.NullInt32
	EpPhysicking       sql.NullInt32
	EpAlchemy          sql.NullInt32
	EpArtificery       sql.NullInt32
	EpNaming           sql.NullInt32
}

type PlayerTurn struct {
	ID              int32
	CreatedAt       time.Time
	PlayerID        sql.NullInt32
	TurnID          sql.NullInt32
	Posts           sql.NullInt32
	PrivateMessages sql.NullInt32
	QualityPosts    sql.NullInt32
	QualityRp       sql.NullInt32
}

type Turn struct {
	ID        int32
	CreatedAt time.Time
	GameID    sql.NullInt32
	Name      sql.NullString
	Writeup   sql.NullString
	Term      sql.NullInt32
	Month     sql.NullInt32
}

type User struct {
	ID        int32
	CreatedAt time.Time
	Username  string
}
