// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ClassType string

const (
	ClassTypeEdemaRuh         ClassType = "edema_ruh"
	ClassTypeCealdishCommoner ClassType = "cealdish_commoner"
	ClassTypeYllishCommoner   ClassType = "yllish_commoner"
	ClassTypeAturanNobleman   ClassType = "aturan_nobleman"
	ClassTypeVintishNobleman  ClassType = "vintish_nobleman"
)

func (e *ClassType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClassType(s)
	case string:
		*e = ClassType(s)
	default:
		return fmt.Errorf("unsupported scan type for ClassType: %T", src)
	}
	return nil
}

type NullClassType struct {
	ClassType ClassType
	Valid     bool // Valid is true if ClassType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClassType) Scan(value interface{}) error {
	if value == nil {
		ns.ClassType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClassType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClassType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClassType), nil
}

func AllClassTypeValues() []ClassType {
	return []ClassType{
		ClassTypeEdemaRuh,
		ClassTypeCealdishCommoner,
		ClassTypeYllishCommoner,
		ClassTypeAturanNobleman,
		ClassTypeVintishNobleman,
	}
}

type LodgingType string

const (
	LodgingTypeStreets         LodgingType = "streets"
	LodgingTypeUnderthing      LodgingType = "underthing"
	LodgingTypeMews            LodgingType = "mews"
	LodgingTypeAnkers          LodgingType = "ankers"
	LodgingTypeKingsDrab       LodgingType = "kings_drab"
	LodgingTypeGreyMan         LodgingType = "grey_man"
	LodgingTypeGoldenPony      LodgingType = "golden_pony"
	LodgingTypeWindyTower      LodgingType = "windy_tower"
	LodgingTypeHorseAndFour    LodgingType = "horse_and_four"
	LodgingTypePearlOfImre     LodgingType = "pearl_of_imre"
	LodgingTypeSpindleAndDraft LodgingType = "spindle_and_draft"
)

func (e *LodgingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LodgingType(s)
	case string:
		*e = LodgingType(s)
	default:
		return fmt.Errorf("unsupported scan type for LodgingType: %T", src)
	}
	return nil
}

type NullLodgingType struct {
	LodgingType LodgingType
	Valid       bool // Valid is true if LodgingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLodgingType) Scan(value interface{}) error {
	if value == nil {
		ns.LodgingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LodgingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLodgingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LodgingType), nil
}

func AllLodgingTypeValues() []LodgingType {
	return []LodgingType{
		LodgingTypeStreets,
		LodgingTypeUnderthing,
		LodgingTypeMews,
		LodgingTypeAnkers,
		LodgingTypeKingsDrab,
		LodgingTypeGreyMan,
		LodgingTypeGoldenPony,
		LodgingTypeWindyTower,
		LodgingTypeHorseAndFour,
		LodgingTypePearlOfImre,
		LodgingTypeSpindleAndDraft,
	}
}

type StartingLodgingType string

const (
	StartingLodgingTypeAnkers          StartingLodgingType = "ankers"
	StartingLodgingTypeKingsDrab       StartingLodgingType = "kings_drab"
	StartingLodgingTypeGoldenPony      StartingLodgingType = "golden_pony"
	StartingLodgingTypeWindyTower      StartingLodgingType = "windy_tower"
	StartingLodgingTypeHorseAndFour    StartingLodgingType = "horse_and_four"
	StartingLodgingTypeSpindleAndDraft StartingLodgingType = "spindle_and_draft"
)

func (e *StartingLodgingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StartingLodgingType(s)
	case string:
		*e = StartingLodgingType(s)
	default:
		return fmt.Errorf("unsupported scan type for StartingLodgingType: %T", src)
	}
	return nil
}

type NullStartingLodgingType struct {
	StartingLodgingType StartingLodgingType
	Valid               bool // Valid is true if StartingLodgingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStartingLodgingType) Scan(value interface{}) error {
	if value == nil {
		ns.StartingLodgingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StartingLodgingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStartingLodgingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StartingLodgingType), nil
}

func AllStartingLodgingTypeValues() []StartingLodgingType {
	return []StartingLodgingType{
		StartingLodgingTypeAnkers,
		StartingLodgingTypeKingsDrab,
		StartingLodgingTypeGoldenPony,
		StartingLodgingTypeWindyTower,
		StartingLodgingTypeHorseAndFour,
		StartingLodgingTypeSpindleAndDraft,
	}
}

type Action struct {
	ID               int32
	CreatedAt        time.Time
	PlayerTurnID     int32
	Lodging          LodgingType
	VisitImre        bool
	AttendUniversity bool
}

type Complaint struct {
	ID        int32
	CreatedAt time.Time
	ActionID  int32
	TargetID  sql.NullInt32
}

type Contract struct {
	ID                 int32
	CreatedAt          time.Time
	GameID             int32
	Name               sql.NullString
	Description        sql.NullString
	RequestingPlayerID sql.NullInt32
	AcceptedPlayerID   sql.NullInt32
	BountyCoin         sql.NullFloat64
	BountyItem         sql.NullString
}

type ElevationPoint struct {
	ID                 int32
	CreatedAt          time.Time
	ActionID           int32
	EpLinguistics      int32
	EpArithmetics      int32
	EpRhetoricAndLogic int32
	EpArchives         int32
	EpSympathy         int32
	EpPhysicking       int32
	EpAlchemy          int32
	EpArtificery       int32
	EpNaming           int32
}

type Game struct {
	ID         int32
	CreatedAt  time.Time
	GameMaster int32
	Name       sql.NullString
	Type       sql.NullString
	TypeNumber sql.NullString
}

type GameTurn struct {
	ID        int32
	CreatedAt time.Time
	GameID    int32
	Name      sql.NullString
	Writeup   sql.NullString
	Term      int32
	Month     int32
	Active    bool
}

type ImreAction struct {
	ID                         int32
	CreatedAt                  time.Time
	ActionID                   int32
	EolianPipes                sql.NullBool
	EolianPractice             sql.NullBool
	GilesLoan                  sql.NullFloat64
	DeviLoan                   sql.NullFloat64
	DiceBet                    sql.NullFloat64
	NoxNahlrout                sql.NullInt32
	NoxCouriers                sql.NullInt32
	NoxBloodless               sql.NullInt32
	NoxGram                    sql.NullInt32
	BlackMarketMommet          sql.NullInt32
	BlackMarketBodyguard       sql.NullBool
	BlackMarketBodygaurdTarget sql.NullInt32
	BlackMarketAssassin        sql.NullBool
	BlackMarketAssassinTarget  sql.NullInt32
	BlackMarketContracts       sql.NullBool
}

type ImreContractAction struct {
	ID           int32
	CreatedAt    time.Time
	ImreActionID int32
	ContractID   sql.NullInt32
}

type Player struct {
	ID         int32
	CreatedAt  time.Time
	UserID     int32
	GameID     int32
	Name       sql.NullString
	Alive      bool
	Skindancer sql.NullBool
	Class      NullClassType
}

type PlayerStatus struct {
	ID                 int32
	CreatedAt          time.Time
	PlayerID           int32
	TurnID             int32
	Sane               bool
	Crockery           bool
	Lodging            sql.NullBool
	Imre               sql.NullBool
	University         sql.NullBool
	Medica             sql.NullBool
	Coin               float64
	EpLinguistics      int32
	EpArithmetics      int32
	EpRhetoricAndLogic int32
	EpArchives         int32
	EpSympathy         int32
	EpPhysicking       int32
	EpAlchemy          int32
	EpArtificery       int32
	EpNaming           int32
}

type PlayerTurn struct {
	ID              int32
	CreatedAt       time.Time
	PlayerID        int32
	TurnID          int32
	Posts           int32
	PrivateMessages int32
	QualityPosts    int32
	QualityRp       int32
}

type User struct {
	ID        int32
	CreatedAt time.Time
	Username  string
}
