// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_turns.sql

package database

import (
	"context"
)

const getPlayerTurnsByID = `-- name: GetPlayerTurnsByID :many
SELECT id, created_at, player_id, turn_id, posts, private_messages, quality_posts, quality_rp FROM player_turns
WHERE player_id = $1
`

func (q *Queries) GetPlayerTurnsByID(ctx context.Context, playerID int32) ([]PlayerTurn, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerTurnsByID, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerTurn
	for rows.Next() {
		var i PlayerTurn
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.PlayerID,
			&i.TurnID,
			&i.Posts,
			&i.PrivateMessages,
			&i.QualityPosts,
			&i.QualityRp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newPlayerTurn = `-- name: NewPlayerTurn :one
INSERT INTO player_turns (player_id, turn_id)
VALUES (
    $1,
    $2
)
RETURNING id, created_at, player_id, turn_id, posts, private_messages, quality_posts, quality_rp
`

type NewPlayerTurnParams struct {
	PlayerID int32
	TurnID   int32
}

func (q *Queries) NewPlayerTurn(ctx context.Context, arg NewPlayerTurnParams) (PlayerTurn, error) {
	row := q.db.QueryRowContext(ctx, newPlayerTurn, arg.PlayerID, arg.TurnID)
	var i PlayerTurn
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.PlayerID,
		&i.TurnID,
		&i.Posts,
		&i.PrivateMessages,
		&i.QualityPosts,
		&i.QualityRp,
	)
	return i, err
}
