// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package database

import (
	"context"
	"database/sql"
)

const clearPlayers = `-- name: ClearPlayers :exec
DELETE FROM players
`

func (q *Queries) ClearPlayers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearPlayers)
	return err
}

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (user_id, game_id, name)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, created_at, user_id, game_id, name, skindancer, class
`

type CreatePlayerParams struct {
	UserID int32
	GameID int32
	Name   sql.NullString
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer, arg.UserID, arg.GameID, arg.Name)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.GameID,
		&i.Name,
		&i.Skindancer,
		&i.Class,
	)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, created_at, user_id, game_id, name, skindancer, class FROM players
WHERE name=$1 LIMIT 1
`

func (q *Queries) GetPlayer(ctx context.Context, name sql.NullString) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, name)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.GameID,
		&i.Name,
		&i.Skindancer,
		&i.Class,
	)
	return i, err
}

const getPlayers = `-- name: GetPlayers :many
SELECT id, created_at, user_id, game_id, name, skindancer, class FROM players
`

func (q *Queries) GetPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.GameID,
			&i.Name,
			&i.Skindancer,
			&i.Class,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
