// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_actions.sql

package database

import (
	"context"
)

const createPlayerAction = `-- name: CreatePlayerAction :one
INSERT INTO actions (player_turn_id)
VALUES (
    $1
)
RETURNING id, created_at, player_turn_id, lodging, visit_imre, attend_university
`

func (q *Queries) CreatePlayerAction(ctx context.Context, playerTurnID int32) (Action, error) {
	row := q.db.QueryRowContext(ctx, createPlayerAction, playerTurnID)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.PlayerTurnID,
		&i.Lodging,
		&i.VisitImre,
		&i.AttendUniversity,
	)
	return i, err
}

const getPlayerActionByPlayerTurnID = `-- name: GetPlayerActionByPlayerTurnID :one
SELECT id, created_at, player_turn_id, lodging, visit_imre, attend_university FROM actions
WHERE player_turn_id=$1 LIMIT 1
`

func (q *Queries) GetPlayerActionByPlayerTurnID(ctx context.Context, playerTurnID int32) (Action, error) {
	row := q.db.QueryRowContext(ctx, getPlayerActionByPlayerTurnID, playerTurnID)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.PlayerTurnID,
		&i.Lodging,
		&i.VisitImre,
		&i.AttendUniversity,
	)
	return i, err
}

const updatePlayerAction = `-- name: UpdatePlayerAction :one
UPDATE actions SET (lodging, visit_imre, attend_university)
= (
    $2,
    $3,
    $4
) WHERE player_turn_id=$1
RETURNING id, created_at, player_turn_id, lodging, visit_imre, attend_university
`

type UpdatePlayerActionParams struct {
	PlayerTurnID     int32
	Lodging          LodgingType
	VisitImre        bool
	AttendUniversity bool
}

func (q *Queries) UpdatePlayerAction(ctx context.Context, arg UpdatePlayerActionParams) (Action, error) {
	row := q.db.QueryRowContext(ctx, updatePlayerAction,
		arg.PlayerTurnID,
		arg.Lodging,
		arg.VisitImre,
		arg.AttendUniversity,
	)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.PlayerTurnID,
		&i.Lodging,
		&i.VisitImre,
		&i.AttendUniversity,
	)
	return i, err
}
